### ISSUE TITLE
Using the code as a standalone script

### ISSUE THREAD

**Issue by akarym-sl** [uhafner/autograding-gitlab-action#12]
Is it possible to use the project independently of GitLab, Docker, Jenkins etc., i.e., run the script on local files?
If so, what is the correct way to set it up and run?

**Comment by uhafner** [comment]
What do you want to achieve? Where should the report be shown? Just in the console?

**Comment by akarym-sl** [comment]
It would be nice to have the report either as console output or in a separate file

**Comment by uhafner** [comment]
This is not possible. All parsers work on files in the moment and the output is created as a markdown comment. 

I am also not sure how much benefit you would get with this approach with respect to the plain compiler output? The reason for this action is to get a summary of all warnings and the warnings marked within the code of the Git provider.
